import * as React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google'; // Or whatever font you prefer
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import MuiThemeProvider from '@/theme/theme-provider';

// Import your minimal global CSS (mostly just CSS reset if needed)
import './globals.css';

// 1. Configure your font
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter', // We use this variable in your theme/index.ts
});

export const metadata: Metadata = {
  title: 'My Custom Design System',
  description: 'Built with Next.js App Router and Material UI Core',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      {/* Suppress hydration warnings on the body tag. 
        MUI injects styles that sometimes cause slight hydration mismatches during dev.
      */}
      <body suppressHydrationWarning>
        {/* 2. The Cache Provider: 
          This collects all the Emotion CSS generated by MUI on the server
          and injects it into the HTML before sending it to the client.
        */}
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          {/* 3. The Theme Provider: Applies your global design tokens */}
          <MuiThemeProvider>{children}</MuiThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}